import type { UserProfile, SkillIntensity } from '../types';
import { skillsById } from '../data/skills';
import { profilesByType } from '../data/mbtiProfiles';

// ─── Helpers ─────────────────────────────────────────────────────────────────

function intensityLabel(intensity: number): string {
  if (intensity >= 90) return 'extremely';
  if (intensity >= 75) return 'strongly';
  if (intensity >= 60) return 'moderately';
  if (intensity >= 40) return 'somewhat';
  return 'lightly';
}

function skillBehaviors(si: SkillIntensity): string {
  const skill = skillsById[si.skillId];
  if (!skill) return '';
  const count = si.intensity >= 75 ? skill.behaviors.length : Math.ceil(skill.behaviors.length * 0.6);
  return skill.behaviors.slice(0, count).map((b) => `  - ${b}`).join('\n');
}

// ─── Main generator ───────────────────────────────────────────────────────────

export function generateSystemPrompt(profile: Partial<UserProfile>): string {
  const { baseType, skills = [], name, communicationPreference, customInstructions } = profile;

  if (!baseType) return '// No base profile selected yet.';

  const mbtiProfile = profilesByType[baseType];
  if (!mbtiProfile) return '// Invalid base profile.';

  const sortedSkills = [...skills].sort((a, b) => b.intensity - a.intensity);
  const dominantSkills = sortedSkills.filter((s) => s.intensity >= 40);

  const profileName = name || `${mbtiProfile.name} Configuration`;

  const skillLines = dominantSkills
    .map((si) => {
      const skill = skillsById[si.skillId];
      return skill
        ? `${skill.name} Skill — ${si.intensity}%\n${skillBehaviors(si)}`
        : '';
    })
    .filter(Boolean)
    .join('\n\n');

  const communicationSection = communicationPreference
    ? `\nCommunication preference: ${communicationPreference}\n`
    : '';

  const customSection = customInstructions
    ? `\nAdditional instructions:\n${customInstructions}\n`
    : '';

  return `# AI Configuration: ${profileName}
# Generated by MBTI AI Skills — mbti-ai-skills.github.io
# ─────────────────────────────────────────────────────

You are an AI configured with an experimental ${baseType}-inspired cognitive profile.

## Base Profile: ${baseType} — ${mbtiProfile.name}

${mbtiProfile.description}

## Cognitive Style

${mbtiProfile.cognitiveStyle}

## Communication Style

${mbtiProfile.communicationStyle}

## Problem-Solving Process

${mbtiProfile.problemSolvingStyle}

## Decision Pattern

${mbtiProfile.decisionStyle}
${communicationSection}
## Active Skills
${dominantSkills.length > 0
  ? `\nThe following cognitive skills are active in this configuration, ordered by intensity:\n\n${skillLines}`
  : '\nNo specific skills configured — operating from base profile defaults.'}

## Core Directives

${sortedSkills.slice(0, 5).map((si, i) => {
  const skill = skillsById[si.skillId];
  return skill ? `${i + 1}. ${intensityLabel(si.intensity).charAt(0).toUpperCase() + intensityLabel(si.intensity).slice(1)} emphasize the ${skill.name} skill: ${skill.shortDescription}` : '';
}).filter(Boolean).join('\n')}
${dominantSkills.length === 0 ? `1. Follow the ${baseType} cognitive profile described above.\n2. Adapt communication to the user's context.\n3. Be clear about what is known vs. assumed.` : ''}

## Important Disclaimer

Do not present MBTI characteristics as scientific facts or fixed traits. This configuration is an experimental AI interaction design pattern — not a psychological diagnosis or scientific measure of capability. Treat all profile descriptions as configurable defaults, not rigid rules.
${customSection}
# ─────────────────────────────────────────────────────
# End of configuration`;
}

// ─── Token estimator (rough approximation) ───────────────────────────────────

export function estimateTokens(text: string): number {
  // Rough approximation: ~4 chars per token
  return Math.ceil(text.length / 4);
}
